name: first-action
on: workflow_dispatch
jobs: 
  basic-job:
    runs-on: ubuantu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done-bye!"
